source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!


target :LiferayScreens do
  # Core
  pod 'Liferay-iOS-SDK', '6.2.0.22'
  pod 'Liferay-OAuth', '0.1.1'
  pod 'MBProgressHUD', '0.9.1'
  pod 'SMXMLDocument', '1.1'
  pod 'ODRefreshControl', '1.2'
  pod 'YapDatabase/SQLCipher', '2.8.2'

  # Login & signup: save credentials
  pod 'KeychainAccess', '3.2.1'

  # UserPortrait
  pod 'CryptoSwift', '1.2.0'

  # DDLForm
  pod 'DTPickerPresenter', '0.2.0'
  pod 'TNRadioButtonGroup', '0.4'
  pod 'MDRadialProgress', '1.3.2'
end


target :LiferayScreensTests do
	pod 'Nocilla'
	pod 'SwiftTryCatch'
end

